#!/bin/bash
branch=$(
  git --version | awk '{
    if ($3 < 2.0)
      print "current";
    else
      print "simple";
  }'
)
pager=""
if [[ `hostname` =~ edison.* ]] ; then
  pager="pager = less -R"
fi
cat <<HEREDOC > gitconfig
[user]
	name = Michael Robson
	email = mprobson@illinois.edu
[color]
	ui = auto
[push]
	default = $branch
[branch]
	autosetuprebase = always
[credential]
	helper = cache --timeout=43200
[alias]
	lg = log --stat
	pul = pull
	gr = log --graph --pretty=oneline --abbrev-commit --full-history
[init]
	templatedir = ~/.git_template
[core]
	autocrlf = input
	editor = vim
	$pager
HEREDOC
